version: '3'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - '6333:6333'
  api:
    build: ./apps/api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./apps/api:/app
    ports:
      - '8000:8000'
    depends_on:
      - qdrant
  ui:
    build: ./apps/ui
    ports:
      - '3000:3000'
