version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:v1.8.4
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      - QDRANT_MODE=remote
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=books
      - EMBED_MODEL=small
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
  ui:
    build:
      context: ./apps/ui
    ports:
      - "3000:3000"
    depends_on:
      - api
