global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:8000

  - job_name: "qdrant"
    metrics_path: /metrics
    static_configs:
      - targets:
          - qdrant:6333

  - job_name: "ollama"
    metrics_path: /metrics
    static_configs:
      - targets:
          - ollama:11434
