apiVersion: apps/v1
kind: Deployment
metadata:
  name: ketabmind-api
  labels:
    app: ketabmind-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ketabmind-api
  template:
    metadata:
      labels:
        app: ketabmind-api
    spec:
      containers:
        - name: api
          image: ghcr.io/ketabmind/fastapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: ketabmind-api-config
            - secretRef:
                name: ketabmind-api-secret
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
